#Data Science HW 2
###Name: Muhammad . ID: 06369
###Email : mm06369@st.habib.edu.pk

In [439]:
import pandas as pd

In [440]:
df = pd.read_csv("580SurveyCleanup.csv")

##Part 1
###Question

####Formatting Columns Names

In [441]:
df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Q11.1,Q11.2,Q11.3,Q11.4,Q12,Q12.1,Q12.2,Q12.3,Q12.4,Q13
0,No.,Time,Status,Duration (Seconds),Access Code,Email Address,IP Address,Country,Region,City / Town / District,...,Some familiarity,Average user,Frequent use for projects,Fluent/expert,Little/none,Some familiarity,Average user,Frequent use for projects,Fluent/expert,What is your goal for learning about data anal...
1,1,10/3/20 5:49 PM,Completed,11646,NaN,NaN,100.36.167.226,United States,Virginia,Fairfax,...,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN
2,2,10/3/20 5:49 PM,Completed,113,NaN,NaN,98.169.26.134,United States,Virginia,Fairfax,...,NaN,1,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN
3,3,10/3/20 5:49 PM,Completed,572,NaN,NaN,98.169.52.23,United States,Virginia,Greenway Downs,...,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,"As part of my work, I have access to a lot of ..."
4,4,10/3/20 5:50 PM,Completed,365,NaN,NaN,69.255.182.253,United States,Virginia,Gainesville,...,NaN,NaN,1,NaN,NaN,1,NaN,NaN,NaN,NaN

Have added various steps in the same cell as this is already in week 2 example. Here according to csv file format the heading names were unnamed, and they were in first row, so I have formatted it.

In [442]:
df_1 = df.iloc[:,1:12]
df_1.columns = df_1.iloc[0]
df_1 = df_1[1:]

In [443]:
df_1.head()

,Time,Status,Duration (Seconds),Access Code,Email Address,IP Address,Country,Region,City / Town / District,Latitude,Longitude
1,10/3/20 5:49 PM,Completed,11646,NaN,NaN,100.36.167.226,United States,Virginia,Fairfax,-77.2891,38.8209
2,10/3/20 5:49 PM,Completed,113,NaN,NaN,98.169.26.134,United States,Virginia,Fairfax,-77.263,38.8605
3,10/3/20 5:49 PM,Completed,572,NaN,NaN,98.169.52.23,United States,Virginia,Greenway Downs,-77.2331,38.9645
4,10/3/20 5:50 PM,Completed,365,NaN,NaN,69.255.182.253,United States,Virginia,Gainesville,-77.6308,38.8175
5,10/3/20 5:51 PM,Completed,92,NaN,NaN,138.88.108.230,United States,NaN,NaN,-97.822,37.751

As we proceed to the questions, we can see that data is not formatted, and for single question we have two columns. We will format the data and bring all the questions data into a single column for that particular question.

Starting with Q1

In [444]:
df2 = df.iloc[:,[12,13]]

In [445]:
df2.columns = df2.iloc[0].astype(str)
df2 = df2[1:]

In [446]:
df3 = df2.loc[:,'2.0':'4.0'].replace(1, pd.Series(df2.columns, df2.columns)).fillna('')
df3 = pd.DataFrame(df3.iloc[:,0] + df3.iloc[:,1])

In [447]:
df3.columns = ['Q1']
df3.head()

    Q1
1  4.0
2  2.0
3  2.0
4  2.0
5  2.0

Now we will format Q2

In [448]:
df4 = df.iloc[:,[14,15]]
df4.columns = df4.iloc[0].astype(str)
df4 = df4[1:].astype(str)

In [449]:

df5 = df4.loc[:, ['Male', 'Female']].replace('1', pd.Series(df4.columns, df4.columns)).replace('nan','')
df5 = pd.DataFrame(df5.iloc[:,0] + df5.iloc[:,1])
df5.columns = ['Q2']
# df5
df6 = df.iloc[:,[16,17]]
df6.columns = df6.iloc[0].astype(str)
df6 = df6[1:].astype(str)
# df6
df6 = df6.loc[:, ['NonBinary', 'Prefer not to answer']].replace('1', pd.Series(df6.columns, df6.columns)).replace('nan','')
df6 = pd.DataFrame(df6.iloc[:,0] + df6.iloc[:,1])
df6.columns = ['Q2']
df6

df7 = pd.DataFrame(df5 + df6)
df7.head()
# df4.columns[0]

                     Q2
1                Female
2                Female
3                  Male
4  Prefer not to answer
5                  Male

In [450]:
df8 = df.iloc[:,[18]]
df8 = df8[1:]


df9 = df.iloc[:, [19]]
df9 = df9[1:]

df10 = df.iloc[:,[20]]
df10 = df10[1:]

df11 = df.iloc[:,[21]]
df11 = df11[1:]

df12 = df.iloc[:,[22]]
df12 = df12[1:]

In [451]:
df13 = df.iloc[:,[23,24,25, 26]]
df13.columns = df13.iloc[0].astype(str)
df13 = df13[1:]

In [452]:
df14 = df13.loc[:, ['Microsoft/Windows', 'Apple/MacBook']].replace('1', pd.Series(df13.columns, df13.columns)).fillna('').replace('2', pd.Series(df13.columns, df13.columns))

In [453]:
df14 = pd.DataFrame(df14.iloc[:,0] + df14.iloc[:,1])
df14.columns = ['Q8']

In [454]:
df15 = df13.loc[:, ['nan']].fillna('')
df15.columns = ['Q8']
df15 = pd.DataFrame(df14 + df15)
df15

                                Q8
1                    Apple/MacBook
2                    Apple/MacBook
3                    Apple/MacBook
4                Microsoft/Windows
5                    Apple/MacBook
6
7                Microsoft/Windows
8
9                Microsoft/Windows
10
11               Microsoft/Windows
12               Microsoft/Windows
13                   Apple/MacBook
14               Microsoft/Windows
15               Microsoft/Windows
16               Microsoft/Windows
17  Microsoft/WindowsApple/MacBook
18               Microsoft/Windows
19               Microsoft/Windows
20                   Apple/MacBook
21               Microsoft/Windows
22               Microsoft/Windows
23  Microsoft/WindowsApple/MacBook
24               Microsoft/Windows
25               Microsoft/Windows
26                               0
27                   Apple/MacBook
28               Microsoft/Windows
29               Microsoft/Windows
30                   Apple/MacBook
31               Microsoft/Windows
32  Microsoft/WindowsApple/MacBook
33               Microsoft/Windows
34               Microsoft/Windows
35               Microsoft/Windows
36                    Acer/Windows

In [455]:
df16 = df.iloc[:,[27,28,29]]
df16.columns = df16.iloc[0].astype(str)
df16 = df16[1:]
df16 = df16.loc[:, ['Yes, Full Time', 'Working, but not Full Time', 'Not Working while attending Mason']].replace('1', pd.Series(df16.columns, df16.columns)).fillna('')
df16 = pd.DataFrame(df16.iloc[:,0] +df16.iloc[:,1] + df16.iloc[:,2])
df16.columns = ['Q9']
df16

                                   Q9
1   Not Working while attending Mason
2          Working, but not Full Time
3                      Yes, Full Time
4   Not Working while attending Mason
5                      Yes, Full Time
6
7          Working, but not Full Time
8
9                      Yes, Full Time
10
11  Not Working while attending Mason
12  Not Working while attending Mason
13         Working, but not Full Time
14  Not Working while attending Mason
15  Not Working while attending Mason
16  Not Working while attending Mason
17                     Yes, Full Time
18  Not Working while attending Mason
19  Not Working while attending Mason
20         Working, but not Full Time
21                     Yes, Full Time
22  Not Working while attending Mason
23         Working, but not Full Time
24  Not Working while attending Mason
25                     Yes, Full Time
26                     Yes, Full Time
27  Not Working while attending Mason
28  Not Working while attending Mason
29  Not Working while attending Mason
30  Not Working while attending Mason
31                     Yes, Full Time
32  Not Working while attending Mason
33                     Yes, Full Time
34                     Yes, Full Time
35  Not Working while attending Mason
36                     Yes, Full Time

In [456]:
df17 = df.iloc[:,[30,31,32,33,34]]
df17.columns = df17.iloc[0].astype(str)
df17 = df17[1:]
df17 = df17.loc[:, ['Little/none', 'Some familiarity', 'Average user', 'Frequent use for projects', 'Fluent/expert']].replace('1', pd.Series(df17.columns, df17.columns)).fillna('')
df17 = pd.DataFrame(df17.iloc[:,0] +df17.iloc[:,1] + df17.iloc[:,2] + df17.iloc[:,3] + df17.iloc[:,4])
df17.columns = ['Q10']
df17

                          Q10
1            Some familiarity
2                Average user
3            Some familiarity
4                Average user
5            Some familiarity
6
7                Average user
8
9            Some familiarity
10
11                Little/none
12  Frequent use for projects
13           Some familiarity
14               Average user
15               Average user
16           Some familiarity
17               Average user
18  Frequent use for projects
19                Little/none
20           Some familiarity
21           Some familiarity
22           Some familiarity
23           Some familiarity
24                Little/none
25               Average user
26               Average user
27               Average user
28               Average user
29               Average user
30               Average user
31                Little/none
32               Average user
33               Average user
34               Average user
35           Some familiarity
36           Some familiarity

In [457]:
df18 = df.iloc[:,[35,36,37, 38, 39]]
df18.columns = df18.iloc[0].astype(str)
df18 = df18[1:]
df18 = df18.loc[:, ['Little/none', 'Some familiarity', 'Average user', 'Frequent use for projects', 'Fluent/expert']].replace('1', pd.Series(df18.columns, df18.columns)).fillna('')
df18 = pd.DataFrame(df18.iloc[:,0] +df18.iloc[:,1] + df18.iloc[:,2] + df18.iloc[:,3] + df18.iloc[:,4])
df18.columns = ['Q11']
df18

                          Q11
1                 Little/none
2                Average user
3                 Little/none
4   Frequent use for projects
5            Some familiarity
6
7                Average user
8
9   Frequent use for projects
10
11                Little/none
12               Average user
13               Average user
14               Average user
15                Little/none
16           Some familiarity
17           Some familiarity
18  Frequent use for projects
19                Little/none
20              Fluent/expert
21           Some familiarity
22                Little/none
23  Frequent use for projects
24                Little/none
25               Average user
26           Some familiarity
27  Frequent use for projects
28  Frequent use for projects
29               Average user
30               Average user
31           Some familiarity
32  Frequent use for projects
33           Some familiarity
34               Average user
35           Some familiarity
36                Little/none

In [458]:
df19 = df.iloc[:,[40,41,42, 43, 44]]
df19.columns = df19.iloc[0].astype(str)
df19 = df19[1:]
df19 = df19.loc[:, ['Little/none', 'Some familiarity', 'Average user', 'Frequent use for projects', 'Fluent/expert']].replace('1', pd.Series(df19.columns, df19.columns)).fillna('')
df19 = pd.DataFrame(df19.iloc[:,0] +df19.iloc[:,1] + df19.iloc[:,2] + df19.iloc[:,3] + df19.iloc[:,4])
df19.columns = ['Q12']
df19

                          Q12
1            Some familiarity
2                 Little/none
3                Average user
4            Some familiarity
5                Average user
6
7                Average user
8
9                Average user
10
11           Some familiarity
12  Frequent use for projects
13               Average user
14               Average user
15                Little/none
16           Some familiarity
17           Some familiarity
18               Average user
19               Average user
20               Average user
21           Some familiarity
22               Average user
23                Little/none
24                Little/none
25               Average user
26           Some familiarity
27               Average user
28               Average user
29               Average user
30  Frequent use for projects
31           Some familiarity
32  Frequent use for projects
33           Some familiarity
34               Average user
35           Some familiarity
36                Little/none

In [459]:
df20 = df.iloc[:,[45]]
df20.fillna('')
df20

                                                  Q13
0   What is your goal for learning about data anal...
1                                                 NaN
2                                                 NaN
3   As part of my work, I have access to a lot of ...
4                                                 NaN
5                                               Learn
6                                                 NaN
7   To deduce meaningful interpretation for Financ...
8                                                 NaN
9                                                 NaN
10                                                NaN
11  To see if it is a field I am interested in pur...
12  To learn and explore cutting edge data technol...
13  Learn to select the appropriate tools to condu...
14                                                NaN
15                                  improve my skills
16  My professional goal is to become a Financial ...
17  able to compliment my Computational Social Sci...
18                                To start a company
19  To be able understand and manipulate data to m...
20  My ultimate goal is to get a job as a sports a...
21  To understand how to properly interpret and di...
22  After graduating data analytics, I want myself...
23  Learning how to appropriately handle large qua...
24  To learn and understand the fundamentals and m...
25  The goal is to learn as many programming/stati...
26     Learning analytics tool and being good at them
27                    I want to be as a data analyst
28  It is very relevant to my PhD research area an...
29  Learn how to handle large amount structured an...
30  To become a good Data Analyst and work for top...
31  Get a better understanding of the granularity ...
32                                                NaN
33                     Learn how data analytics works
34                  Advance my career in data science
35                                 Getting a good job
36                         to use the skills at work.


Final dataframe from the formatted columns

In [460]:
newdf = pd.concat([df_1, df3, df7, df8, df9, df10, df11, df12,df15, df16, df17, df18, df19, df20 ], axis = 1)
newdf = newdf[:len(newdf)-1]
newdf.to_csv("formated.csv")

#Part 2

In [461]:
data = pd.read_csv('formated.csv')

Fetching columns that have null values

In [462]:
data.columns[data.isna().any()]

Index(['Access Code', 'Email Address', 'Region', 'City / Town / District',
       'Q4', 'Q5', 'Q6', 'Q7', 'Q8', 'Q9', 'Q10', 'Q11', 'Q12', 'Q13'],
      dtype='object')

Dropping those two columns because it is completely null.


---

In [463]:
data.drop(columns=['Access Code', 'Email Address'], inplace=True)

Taking mode of values in column of 'Region', and placing that value in any empty cell.

In [464]:
repeated_region = data["Region"].mode()
data["Region"].fillna(repeated_region.values[0], inplace=True)
col = data.columns[data.isna().any()].tolist()
data['Region']

0     Virginia
1     Virginia
2     Virginia
3     Virginia
4     Virginia
5     Virginia
6     Virginia
7     Virginia
8     Virginia
9        Texas
10    Maryland
11    Virginia
12    Virginia
13    Virginia
14    Maryland
15    Maryland
16    Virginia
17    Virginia
18    Virginia
19    Virginia
20    Virginia
21    Virginia
22    Maryland
23    Virginia
24    Virginia
25    Virginia
26    Virginia
27    Virginia
28    Maryland
29    Virginia
30    Virginia
31    Virginia
32    Virginia
33    Virginia
34    Maryland
35    Virginia
Name: Region, dtype: object

Taking mode of values in 'City/ Town/ District' column, and placing the mode value in any empty cell.

In [465]:
repeated_region = data["City / Town / District"].mode()
data["City / Town / District"].fillna(repeated_region.values[0], inplace=True)
col = data.columns[data.isna().any()].tolist()
data["City / Town / District"]

0            Fairfax
1            Fairfax
2     Greenway Downs
3        Gainesville
4            Fairfax
5             Reston
6          Arlington
7            Ashburn
8         Woodbridge
9            Fairfax
10       Takoma Park
11           Fairfax
12         Chantilly
13             Burke
14       Hyattsville
15         Baltimore
16         Arlington
17       Springfield
18        Woodbridge
19          Rustburg
20           Fairfax
21            Reston
22         Baltimore
23           Fairfax
24           Fairfax
25             Burke
26           Fairfax
27             Burke
28         Baltimore
29       Springfield
30            Lorton
31             Burke
32      Falls Church
33           Fairfax
34         Frederick
35           Fairfax
Name: City / Town / District, dtype: object

One of the age value is 1993 which is year. So making sure if year is entered subtract if from 2023 and enter the age

In [466]:
import numpy as np


data['Q3'] = data['Q3'].str.replace(' ', '')
data["Q3"] = data['Q3'].astype(int)
data['Q3'] = np.where(data['Q3'] > 100, 2023 - data['Q3'], data['Q3'])
data['Q3']

0     23
1     24
2     40
3     26
4     30
5     25
6     24
7     30
8     24
9     26
10    24
11    25
12    25
13    23
14    31
15    26
16    40
17    23
18    25
19    22
20    23
21    25
22    22
23    23
24    27
25    28
26    23
27    35
28    27
29    25
30    55
31    23
32    30
33    23
34    24
35    28
Name: Q3, dtype: int64

In Q4 we have height in inches. We will take the mean of all the height data, and fill the column with null value with the mean value. Also I will correct some anomalies in the data like 6l, and 7O.

In [467]:
data['Q4'] = np.where(data['Q4'] == "7O", "70", data['Q4'])
data['Q4'] = np.where(data['Q4'] == "6l", "61", data['Q4'])
data['Q4'] = data['Q4'].astype(float)

mean = data["Q4"].mean()
data["Q4"].fillna(mean, inplace=True)
data['Q4']

0     63.00
1     59.00
2     70.00
3     66.00
4     70.00
5     65.72
6     70.00
7      5.20
8     71.00
9     71.00
10    66.00
11    66.00
12    69.00
13    66.00
14    67.00
15    72.00
16    68.00
17    60.00
18    67.00
19    67.00
20    74.00
21    65.00
22    67.00
23    75.00
24    67.00
25    68.00
26    72.00
27    61.00
28    64.00
29    71.00
30    56.00
31    70.00
32    70.00
33    73.00
34    68.00
35    66.00
Name: Q4, dtype: float64

Taking mode for values in Q6, and assigning it to null values.

In [468]:
mode_value = data["Q5"].mode()
data["Q5"].fillna(mode_value.values[0], inplace=True)
data['Q5'] = data['Q5'].str.strip()
data['Q5'] = data['Q5'].str.upper()
data['Q5'] = np.where(data['Q5'] == 'UNITED STATES ; PAKISTAN',
                     'UNITED STATES', data['Q5'])

data['Q5']

0            TAIWAN
1             INDIA
2             INDIA
3       SOUTH KOREA
4                US
5             INDIA
6          PAKISTAN
7             INDIA
8             CHINA
9        UZBEKISTAN
10              USA
11            INDIA
12          ROMANIA
13            INDIA
14            CHINA
15       UZBEKISTAN
16              USA
17            INDIA
18         ETHIOPIA
19    UNITED STATES
20    UNITED STATES
21            INDIA
22              USA
23          NIGERIA
24              USA
25           TAIWAN
26            INDIA
27          NIGERIA
28            INDIA
29            INDIA
30    UNITED STATES
31            INDIA
32    UNITED STATES
33              USA
34          VIETNAM
35       UZBEKISTAN
Name: Q5, dtype: object

In [469]:
mode_value = data["Q6"].mode()
data["Q6"].fillna(repeated_region.values[0], inplace=True)
data['Q6'] = data['Q6'].str.strip()
data['Q6'] = data['Q6'].str.upper()
data['Q6'] = data['Q6'].replace('YES',np.NaN)
data["Q6"].fillna(mode_value.values[0], inplace=True)
data['Q6']

0                    ECONOMICS
1                      FINANCE
2        COMPUTER APPLICATIONS
3          BUSINESS MANAGEMENT
4                    Economics
5                      FAIRFAX
6                      FINANCE
7                      FAIRFAX
8                     ECONOMIC
9       ECONOMICS WITH FINANCE
10                         BIT
11        COMPUTER ENGINEERING
12                     BIOLOGY
13                         CSE
14                  MANAGEMENT
15      ECONOMICS WITH FINANCE
16                   ECONOMICS
17                 ENGINEERING
18         ACCOUNTING AND ISOM
19                  STATISTICS
20            COMPUTER SCIENCE
21            COMPUTER SCIENCE
22    MATHEMATICS & STATISTICS
23                   ECONOMICS
24         SYSTEMS ENGINEERING
25           CIVIL ENGINEERING
26                         ECE
27          QUANTITY SURVEYING
28     BACHELOR OF ENGINEERING
29                B.TECH IN CS
30               BS ACCOUNTING
31     BACHELOR OF ENGINEERING
32    CRIMINOLOGY LAW AND SOCI
33                   ECONOMICS
34                     FINANCE
35                  PSYCHOLOGY
Name: Q6, dtype: object

In [470]:
repeated_region = data["Q7"].mode()
data["Q7"].fillna(repeated_region.values[0], inplace=True)
data['Q7']

0     2021-12-31
1     2021-05-01
2     2022-06-01
3     2021-12-31
4     2021-01-01
5     2021-12-20
6     2022-07-15
7     2021-12-20
8     2021-12-15
9     2021-12-20
10    2022-05-01
11    2021-05-31
12    2021-08-26
13    2021-12-25
14    2021-12-31
15    2022-05-01
16    2022-05-31
17    2021-01-12
18    2021-12-20
19    2021-12-20
20    2022-05-01
21    2022-04-16
22    2021-12-18
23    2021-05-14
24    2022-12-19
25    2021-05-30
26    2021-12-11
27    2023-05-24
28    2021-12-30
29    2021-12-15
30    2021-05-01
31    2021-12-21
32    2021-12-18
33    2022-05-15
34    2022-12-12
35    2021-12-20
Name: Q7, dtype: object

In Q8, correcting the values in the column, and taking mode of the values and using it to fill null values

In [471]:

data['Q8'] = np.where(data['Q8'] == '0', 'Microsoft/Windows', data['Q8'])

mode_value = data["Q8"].mode()
data["Q8"].fillna(mode_value.values[0], inplace=True)
data['Q8']

0                      Apple/MacBook
1                      Apple/MacBook
2                      Apple/MacBook
3                  Microsoft/Windows
4                      Apple/MacBook
5                  Microsoft/Windows
6                  Microsoft/Windows
7                  Microsoft/Windows
8                  Microsoft/Windows
9                  Microsoft/Windows
10                 Microsoft/Windows
11                 Microsoft/Windows
12                     Apple/MacBook
13                 Microsoft/Windows
14                 Microsoft/Windows
15                 Microsoft/Windows
16    Microsoft/WindowsApple/MacBook
17                 Microsoft/Windows
18                 Microsoft/Windows
19                     Apple/MacBook
20                 Microsoft/Windows
21                 Microsoft/Windows
22    Microsoft/WindowsApple/MacBook
23                 Microsoft/Windows
24                 Microsoft/Windows
25                 Microsoft/Windows
26                     Apple/MacBook
27                 Microsoft/Windows
28                 Microsoft/Windows
29                     Apple/MacBook
30                 Microsoft/Windows
31    Microsoft/WindowsApple/MacBook
32                 Microsoft/Windows
33                 Microsoft/Windows
34                 Microsoft/Windows
35                      Acer/Windows
Name: Q8, dtype: object

In [472]:
mode_value = data["Q9"].mode()
data["Q9"].fillna(mode_value.values[0], inplace=True)
data["Q9"]

0     Not Working while attending Mason
1            Working, but not Full Time
2                        Yes, Full Time
3     Not Working while attending Mason
4                        Yes, Full Time
5     Not Working while attending Mason
6            Working, but not Full Time
7     Not Working while attending Mason
8                        Yes, Full Time
9     Not Working while attending Mason
10    Not Working while attending Mason
11    Not Working while attending Mason
12           Working, but not Full Time
13    Not Working while attending Mason
14    Not Working while attending Mason
15    Not Working while attending Mason
16                       Yes, Full Time
17    Not Working while attending Mason
18    Not Working while attending Mason
19           Working, but not Full Time
20                       Yes, Full Time
21    Not Working while attending Mason
22           Working, but not Full Time
23    Not Working while attending Mason
24                       Yes, Full Time
25                       Yes, Full Time
26    Not Working while attending Mason
27    Not Working while attending Mason
28    Not Working while attending Mason
29    Not Working while attending Mason
30                       Yes, Full Time
31    Not Working while attending Mason
32                       Yes, Full Time
33                       Yes, Full Time
34    Not Working while attending Mason
35                       Yes, Full Time
Name: Q9, dtype: object

In [473]:
mode_value = data["Q10"].mode()
data["Q10"].fillna(mode_value.values[0], inplace=True)
data["Q10"]

0              Some familiarity
1                  Average user
2              Some familiarity
3                  Average user
4              Some familiarity
5                  Average user
6                  Average user
7                  Average user
8              Some familiarity
9                  Average user
10                  Little/none
11    Frequent use for projects
12             Some familiarity
13                 Average user
14                 Average user
15             Some familiarity
16                 Average user
17    Frequent use for projects
18                  Little/none
19             Some familiarity
20             Some familiarity
21             Some familiarity
22             Some familiarity
23                  Little/none
24                 Average user
25                 Average user
26                 Average user
27                 Average user
28                 Average user
29                 Average user
30                  Little/none
31                 Average user
32                 Average user
33                 Average user
34             Some familiarity
35             Some familiarity
Name: Q10, dtype: object

In [474]:
mode_value = data["Q11"].mode()
data["Q11"].fillna(mode_value.values[0], inplace=True)
data["Q11"]

0                   Little/none
1                  Average user
2                   Little/none
3     Frequent use for projects
4              Some familiarity
5                  Average user
6                  Average user
7                  Average user
8     Frequent use for projects
9                  Average user
10                  Little/none
11                 Average user
12                 Average user
13                 Average user
14                  Little/none
15             Some familiarity
16             Some familiarity
17    Frequent use for projects
18                  Little/none
19                Fluent/expert
20             Some familiarity
21                  Little/none
22    Frequent use for projects
23                  Little/none
24                 Average user
25             Some familiarity
26    Frequent use for projects
27    Frequent use for projects
28                 Average user
29                 Average user
30             Some familiarity
31    Frequent use for projects
32             Some familiarity
33                 Average user
34             Some familiarity
35                  Little/none
Name: Q11, dtype: object

In [475]:
mode_value = data["Q12"].mode()
data["Q12"].fillna(mode_value.values[0], inplace=True)
data["Q12"]

0              Some familiarity
1                   Little/none
2                  Average user
3              Some familiarity
4                  Average user
5                  Average user
6                  Average user
7                  Average user
8                  Average user
9                  Average user
10             Some familiarity
11    Frequent use for projects
12                 Average user
13                 Average user
14                  Little/none
15             Some familiarity
16             Some familiarity
17                 Average user
18                 Average user
19                 Average user
20             Some familiarity
21                 Average user
22                  Little/none
23                  Little/none
24                 Average user
25             Some familiarity
26                 Average user
27                 Average user
28                 Average user
29    Frequent use for projects
30             Some familiarity
31    Frequent use for projects
32             Some familiarity
33                 Average user
34             Some familiarity
35                  Little/none
Name: Q12, dtype: object

In [476]:
data["Q13"].fillna('', inplace=True)
data['Q13']

0
1
2     As part of my work, I have access to a lot of ...
3
4                                                 Learn
5
6     To deduce meaningful interpretation for Financ...
7
8
9
10    To see if it is a field I am interested in pur...
11    To learn and explore cutting edge data technol...
12    Learn to select the appropriate tools to condu...
13
14                                    improve my skills
15    My professional goal is to become a Financial ...
16    able to compliment my Computational Social Sci...
17                                  To start a company
18    To be able understand and manipulate data to m...
19    My ultimate goal is to get a job as a sports a...
20    To understand how to properly interpret and di...
21    After graduating data analytics, I want myself...
22    Learning how to appropriately handle large qua...
23    To learn and understand the fundamentals and m...
24    The goal is to learn as many programming/stati...
25       Learning analytics tool and being good at them
26                      I want to be as a data analyst
27    It is very relevant to my PhD research area an...
28    Learn how to handle large amount structured an...
29    To become a good Data Analyst and work for top...
30    Get a better understanding of the granularity ...
31
32                       Learn how data analytics works
33                    Advance my career in data science
34                                   Getting a good job
35                           to use the skills at work.
Name: Q13, dtype: object

In [477]:
data.to_csv("cleaned.csv")

#Part 3

In [478]:
data = pd.read_csv("cleaned.csv")

In [479]:
data['Q1'].describe()

count    36.000000
mean      2.888889
std       1.007905
min       2.000000
25%       2.000000
50%       2.000000
75%       4.000000
max       4.000000
Name: Q1, dtype: float64

###Analysis Q1

According to the data, the mean is closer to 2, and the median is also closer to 2 which indicates that most students belong to section 02.

In [480]:
data['Q2'].describe()

count       36
unique       4
top       Male
freq        18
Name: Q2, dtype: object

###Analysis Q2

According to the data, there are more number of males.

In [481]:
data['Q3'].describe()

count    36.000000
mean     27.138889
std       6.503418
min      22.000000
25%      23.000000
50%      25.000000
75%      28.000000
max      55.000000
Name: Q3, dtype: float64

###Analysis Q3
If we look at the mean, the average age of students is 27, while the most old student is 55 years old, and the most young student is 22 years old.

In [482]:
data['Q4'].describe()

count    36.000000
mean     65.720000
std      11.167422
min       5.200000
25%      65.930000
50%      67.000000
75%      70.000000
max      75.000000
Name: Q4, dtype: float64

###Analysis Q4

The mean is 66 which indicates that the average height of students is 65. The most tallest student is 75, and the most shortest student is 5.

In [483]:
data['Q5'].describe()

count        36
unique       13
top       INDIA
freq         12
Name: Q5, dtype: object

###Analysis Q5

Majority of the students belong from India, while there are around 13 unique destinations.

In [484]:
data['Q6'].describe()

count            36
unique           27
top       ECONOMICS
freq              4
Name: Q6, dtype: object

###Analysis Q6
The most enrolled subject is Economics.

In [485]:
data['Q7'].describe()

count             36
unique            24
top       2021-12-20
freq               6
Name: Q7, dtype: object

###Analysis Q7
The graduating data for the students is 20-12-2021

In [486]:
data['Q8'].describe()

count                    36
unique                    4
top       Microsoft/Windows
freq                     24
Name: Q8, dtype: object

###Analysis Q8

The most used operating system is Microsoft Windows.

In [487]:
data['Q9'].describe()

count                                    36
unique                                    3
top       Not Working while attending Mason
freq                                     20
Name: Q9, dtype: object

###Analysis Q9

Most students don't work while studying at Mason, as it is the most frequent selected option

In [488]:
data['Q10'].describe()

count               36
unique               4
top       Average user
freq                18
Name: Q10, dtype: object

###Analysis Q10

Most of the students have average coding capabilities in python.

In [489]:
data['Q11'].describe()

count               36
unique               5
top       Average user
freq                12
Name: Q11, dtype: object

###Analysis Q11
Most students have average coding capability in R.

In [490]:
data['Q12'].describe()

count               36
unique               4
top       Average user
freq                18
Name: Q12, dtype: object

###Analysis Q12

Most students have average coding capability in SQL.